### ISSUE TITLE
erreur 401

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-suivi-perso#35]
==> /var/log/laclasse-suiviperso/puma.log <==
E, [2015-09-28T14:25:49.109926 #38567] ERROR -- : Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
E, [2015-09-28T14:25:49.662921 #38564] ERROR -- : Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
D, [2015-09-28T14:25:50.562101 #38564] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.266744815 s
D, [2015-09-28T14:25:50.562915 #38564] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.266744815 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

==> /var/log/laclasse-suiviperso/puma.log <==
E, [2015-09-28T14:25:50.568724 #38564] ERROR -- : Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
["/home/erasme/laclasse-suiviperso/helpers/error_helpers.rb:11:in `raise_crud_error'", "/home/erasme/laclasse-suiviperso/objects/carnet.rb:63:in `rescue in read'", "/home/erasme/laclasse-suiviperso/objects/carnet.rb:53:in `read'", "/home/erasme/laclasse-suiviperso/api/rights.rb:33:in `block in <class:RightsApi>'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `block in generate_api_method'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `run'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:195:in `block in call!'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/middleware/base.rb:24:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/middleware/base.rb:24:in `call!'"]
D, [2015-09-28T14:25:50.581375 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.280313127 s
D, [2015-09-28T14:25:50.582237 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.280313127 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

==> /var/log/laclasse-suiviperso/puma.log <==
E, [2015-09-28T14:25:50.585080 #38567] ERROR -- : Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
["/home/erasme/laclasse-suiviperso/helpers/error_helpers.rb:11:in `raise_crud_error'", "/home/erasme/laclasse-suiviperso/objects/carnet.rb:63:in `rescue in read'", "/home/erasme/laclasse-suiviperso/objects/carnet.rb:53:in `read'", "/home/erasme/laclasse-suiviperso/api/rights.rb:33:in `block in <class:RightsApi>'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:47:in `block in generate_api_method'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:247:in `run'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/endpoint.rb:195:in `block in call!'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/middleware/base.rb:24:in `call'", "/home/erasme/bundler_shared/ruby/2.2.0/gems/grape-0.11.0/lib/grape/middleware/base.rb:24:in `call!'"]
E, [2015-09-28T14:25:50.755553 #38560] ERROR -- : Une erreur dans la fonction read de la classe Carnet sur la récupération d'un carnet
D, [2015-09-28T14:25:50.953213 #38560] DEBUG -- : Call to service_annuaire_regroupement  with url '210' took 0.187718925 s
D, [2015-09-28T14:25:50.953645 #38560] DEBUG -- : Call to service_annuaire_regroupement  with url '210' took 0.187718925 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

==> /var/log/laclasse-suiviperso/puma.log <==
D, [2015-09-28T14:25:51.019082 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.258358793 s
D, [2015-09-28T14:25:51.019607 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69777' took 0.258358793 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

==> /var/log/laclasse-suiviperso/puma.log <==
D, [2015-09-28T14:25:51.474810 #38560] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69454' took 0.263589498 s
D, [2015-09-28T14:25:51.475273 #38560] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69454' took 0.263589498 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

==> /var/log/laclasse-suiviperso/puma.log <==
D, [2015-09-28T14:25:51.508603 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69455' took 0.264241968 s
D, [2015-09-28T14:25:51.509432 #38567] DEBUG -- : Call to service_annuaire_user  with url 'VBQ69455' took 0.264241968 s

==> /var/log/laclasse-suiviperso/puma_error.log <==
LogStashLogger::Device::UDP - Errno::ECONNREFUSED - Connection refused

**Comment by cycojesus** [comment]
non reproductible après redémarrage de l'application
